Repository Umweltzone/roadsigns, pull requests merged in 2020-10, with the labels that each got.

#12 Adding Portuguese translation
  roadsigns/src/main/res/values-pt/strings.xml
Labels: Hacktoberfest, Translation

#15 Update project setup (Kotlin 1.4.10, SDK 29)
  CHANGELOG.md
  app/build.gradle
  app/src/main/kotlin/info/metadude/kotlin/library/roadsigns/demo/DemoActivity.kt
  buildSrc/src/main/kotlin/info/metadude/kotlin/library/roadsigns/Dependencies.kt
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  roadsigns/build.gradle
  roadsigns/src/main/kotlin/info/metadude/kotlin/library/roadsigns/RoadSign.kt
Labels: Project setup

#16 Replace deprecated ActivityTestRule with ActivityScenarioRule.
  app/build.gradle
  app/src/androidTest/java/info/metadude/kotlin/library/roadsigns/demo/DemoActivityParameterizedTest.kt
  app/src/androidTest/java/info/metadude/kotlin/library/roadsigns/demo/DemoActivityTest.kt
  buildSrc/src/main/kotlin/info/metadude/kotlin/library/roadsigns/Dependencies.kt
Labels: Housekeeping

#17 Add Swedish translation
  roadsigns/src/main/res/values-sv/strings.xml
Labels: Hacktoberfest, Translation

#18 Translated strings.xml into Spanish
  CHANGELOG.md
  README.md
  roadsigns/src/main/res/values-es/strings.xml
Labels: Hacktoberfest, Translation

#19 Added Polish translation
  CHANGELOG.md
  README.md
  roadsigns/src/main/res/values-pl/strings.xml
Labels: Hacktoberfest, Translation

#20 French translation
  CHANGELOG.md
  README.md
  roadsigns/src/main/res/values-fr/strings.xml
Labels: Hacktoberfest, Translation

#21 Add Danish translation
  CHANGELOG.md
  README.md
  roadsigns/src/main/res/values-da/strings.xml
Labels: Hacktoberfest, Translation
